[package]
name = "devcontainer-rs"
description = "A parser for the devcontainer.json spec"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
